[features]
seeds = false
skip-lint = false
[programs.devnet]
gif_portal_anchor = "D6vuZhHnxDWKCRmDprhYrV6otUtS4NdrkMTTQQzS6Zdm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/willowsenator/.config/solana/id.json"

[scripts]
test = "node tests/gif-portal-anchor.js"
