[features]
seeds = false
skip-lint = false
[programs.devnet]
gif_portal_anchor = "FzwXxcH2FVRaqXtXx41N8vxpKPoQY3wRPnJJ7TMjP3da"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/willowsenator/.config/solana/id.json"

[scripts]
test = "node tests/gif-portal-anchor.js"
